# Generated by Django 6.1.1 on 2026-09-29 17:21

import django.core.validators
import django.db.models.deletion
import pulse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[pulse.models.validate_not_blank])),
                ('share_token', models.CharField(default=pulse.models.generate_share_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_key', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_week_key', message='Enter a week in the form YYYY-Www, e.g. 2026-W40.', regex='\\A\\d{4}-W(0[1-9]|[1-4]\\d|5[0-3])\\Z')])),
                ('workload', pulse.models.RatingField(validators=[pulse.models.validate_rating], verbose_name='My workload is manageable')),
                ('clarity', pulse.models.RatingField(validators=[pulse.models.validate_rating], verbose_name='Our goals and priorities are clear')),
                ('collaboration', pulse.models.RatingField(validators=[pulse.models.validate_rating], verbose_name='We work well together')),
                ('progress', pulse.models.RatingField(validators=[pulse.models.validate_rating], verbose_name='I am confident we will deliver')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pulse.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'week_key'], name='pulse_sub_project_week_idx')],
            },
        ),
    ]
