"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import zoneinfo
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n412pf@i^k-(_+z^6b1of!hh9tj=^763t+il5#c&qewf13ovxf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pulse',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def database_path():
    """Return the SQLite file path, from PULSE_DB_PATH or the project root."""
    value = os.environ.get('PULSE_DB_PATH')
    if value is None:
        return BASE_DIR / 'db.sqlite3'
    if not value.strip():
        raise ImproperlyConfigured('PULSE_DB_PATH is set but empty; set it to an absolute file path or unset it.')
    path = Path(value)
    if not path.is_absolute():
        raise ImproperlyConfigured(f'PULSE_DB_PATH must be an absolute path, got {value!r}.')
    if path.is_dir():
        raise ImproperlyConfigured(f'PULSE_DB_PATH points at a directory, not a file: {path}')
    if not path.parent.is_dir():
        raise ImproperlyConfigured(f'The directory for PULSE_DB_PATH does not exist: {path}')
    return path


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': database_path(),
        'OPTIONS': {
            # Run on every new connection.
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA secure_delete=ON',
            # Take the write lock when a transaction starts, so a "check, then
            # insert" sequence cannot race (first-user registration, #6).
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password hashing: Argon2 for new passwords; PBKDF2 stays so old hashes still
# verify and are upgraded to Argon2 at the next login.

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 12},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'


def time_zone():
    """Return the instance time zone name, from PULSE_TIME_ZONE (default UTC)."""
    value = os.environ.get('PULSE_TIME_ZONE')
    if value is None:
        return 'UTC'
    name = value.strip()
    if not name:
        raise ImproperlyConfigured('PULSE_TIME_ZONE is set but empty; set it to a time zone name such as Europe/Zurich or unset it.')
    try:
        zoneinfo.ZoneInfo(name)
    except (zoneinfo.ZoneInfoNotFoundError, ValueError):
        raise ImproperlyConfigured(f'PULSE_TIME_ZONE is not a known time zone name: {value!r}.') from None
    return name


TIME_ZONE = time_zone()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Pulse
# Read these through pulse.conf or django.conf.settings, never os.environ.

def _int_from_env(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except ValueError:
        raise ImproperlyConfigured(f'{name} must be an integer, got {value!r}.') from None


def scale_bounds():
    """Return (min, max) of the rating scale, from PULSE_SCALE_MIN/PULSE_SCALE_MAX (default 1 to 5)."""
    minimum = _int_from_env('PULSE_SCALE_MIN', 1)
    maximum = _int_from_env('PULSE_SCALE_MAX', 5)
    if minimum < 0:
        raise ImproperlyConfigured(f'PULSE_SCALE_MIN must not be negative, got {minimum}.')
    if minimum >= maximum:
        raise ImproperlyConfigured(
            f'PULSE_SCALE_MIN ({minimum}) must be less than PULSE_SCALE_MAX ({maximum}).'
        )
    # At most 11 values, so the rating form stays quick to fill in.
    if maximum - minimum + 1 > 11:
        raise ImproperlyConfigured(
            f'PULSE_SCALE_MIN ({minimum}) to PULSE_SCALE_MAX ({maximum}) gives {maximum - minimum + 1} values; '
            'at most 11 are allowed.'
        )
    return minimum, maximum


def anonymity_threshold():
    """Return the response count below which anonymity is limited, from PULSE_ANONYMITY_THRESHOLD (default 5)."""
    threshold = _int_from_env('PULSE_ANONYMITY_THRESHOLD', 5)
    if threshold < 1:
        raise ImproperlyConfigured(f'PULSE_ANONYMITY_THRESHOLD must be at least 1, got {threshold}.')
    return threshold


PULSE_SCALE_MIN, PULSE_SCALE_MAX = scale_bounds()

PULSE_ANONYMITY_THRESHOLD = anonymity_threshold()


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Authentication
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/projects/'
LOGOUT_REDIRECT_URL = '/login/'
